spring.application.name=contact-manager

# Use Render environment variables
spring.datasource.url=jdbc:postgresql://dpg-d72f3egule4c73e3s3j0-a.oregon-postgres.render.com:5432/contactdb_24wg
spring.datasource.username=vivek
spring.datasource.password=kfD3Wo80Fk4cn9CDXTn0sUKkTTJA5nJb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# IMPORTANT for Render
server.port=${PORT:8080}